source 'https://supermarket.chef.io'

cookbook 'build-essential', '~> 8.2.1'
cookbook 'apache2', '~> 5.0.0'
cookbook 'apt', '~> 7.1.1'
cookbook 'composer', '~> 2.6.1'
cookbook 'packagecloud', '~> 1.0.1'
cookbook 'redisio', '~> 3.0.0'
cookbook 'phantomjs2', '~> 1.1.0'
cookbook 'imagemagick', '~> 0.2.3'
cookbook 'perl', '~> 7.0.1'
