source 'https://supermarket.chef.io'

cookbook 'build-essential', '~> 8.2.1'
cookbook 'apache2', '~> 8.0.2'
cookbook 'apt', '~> 7.2.0'
cookbook 'composer', '~> 2.6.1'
cookbook 'packagecloud', '~> 1.0.1'
cookbook 'redisio', '~> 4.0.0'
cookbook 'imagemagick', '~> 0.2.3'
cookbook 'perl', '~> 7.0.1'
cookbook 'chrome', '~> 4.0.2'
cookbook 'nodejs', '~> 6.0.0'
cookbook 'nvm', '~> 0.1.7'