---
driver:
  name: vagrant
  synced_folders:
    - ['../../plugins/', '/vagrant/plugins/']
    - ['test/integration/fixtures/docroot/', '/srv/piwik/']

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[piwik::default]
    attributes:
